#!/bin/bash

docker run \
  -it \
  --rm \
  --name devcont \
  -v ~/dockvol:/dockvol \
  -v ~/.gitconfig:/etc/gitconfig \
  -p 8888:8888 \
  -p 8000:8000 \
  -p 4000:4000 \
  --network="host" \
  devim
